import Head from "next/head"
import Menu from "../components/tasks/menu"

export default function Tasks() {
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu/>
        </>
    )
}